[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version %}\
    ## [{{ version | replace(from="op-rbuilder/v", to="") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/flashbots/op-rbuilder/commit/{{ commit.id }}) {{ commit.message | split(pat="\n") | first | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
footer = ""
trim = true

[git]
commit_preprocessors = [
    { pattern = '\(#([0-9]+)\)', replace = "([#${1}](https://github.com/flashbots/op-rbuilder/pull/${1}))" },
]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { breaking = true, group = "⚠️ Breaking Changes" },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(release\\)", skip = true },
    { message = ".*", group = "Miscellaneous" },
]
protect_breaking_commits = true
filter_commits = false
tag_pattern = "op-rbuilder/v[0-9]+\\.[0-9]+\\.[0-9]+$"
